version: 0.2


phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 581921480440.dkr.ecr.ap-south-1.amazonaws.com
      - REPOSITORY_URI=581921480440.dkr.ecr.ap-south-1.amazonaws.com/staging/backend
      - IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:-latest}
      - CONTAINER_NAME=staging-backend
  build:
    commands:
      - echo Build started on date
      - echo Building the Docker image...
      - docker build -t stockregister:$IMAGE_TAG .
      - docker tag stockregister:$IMAGE_TAG $REPOSITORY_URI:$IMAGE_TAG
      - docker tag stockregister:$IMAGE_TAG $REPOSITORY_URI:latest
  post_build:
    commands:
      - echo Build completed on date
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - docker push $REPOSITORY_URI:latest
      - echo Creating imagedefinitions.json...
      - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME $REPOSITORY_URI:$IMAGE_TAG > imagedefinitions.json
      - echo Verifying imagedefinitions.json...
      - cat imagedefinitions.json
artifacts:
    files: 
    - imagedefinitions.json