name: Docker Image CI

on:
  push:
    branches: [ "main" ]
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Login to aws ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build docker image
      run: |
        docker build -t staging/backend .

    - name: Tag docker image
      run: |
        REPO_URI="${{ steps.login-ecr.outputs.registry }}/staging/backend"
        docker tag staging/backend:latest $REPO_URI:latest
        docker push $REPO_URI:latest
